---
kind: pipeline
name: build and publish

steps:
  - name: build and publish
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.internal.walbeck.it/walbeck-it/nextcloud-spreed-signaling
      registry: docker.internal.walbeck.it
      tags:
        - "latest"
  
  - name: notify
    image: plugins/matrix
    settings:
        homeserver: https://matrix.mwalbeck.org
        roomid:
        from_secret: matrix_roomid
        username:
        from_secret: matrix_username
        password:
        from_secret: matrix_password
    when:
        status:
        - success
        - failure

trigger:
  branch:
    - master
  event:
    - push

---
kind: pipeline
name: test

steps:
  - name: build test
    image: plugins/docker
    settings:
      dockerfile: Dockerfile
      repo: docker.internal.walbeck.it/walbeck-it/nextcloud-spreed-signaling
      registry: docker.internal.walbeck.it
      dry_run: true

trigger:
  event:
    - pull_request
