---
kind: pipeline
name: nextcloud-spreed-signaling

steps:
  - name: docker
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: docker.internal.walbeck.it/walbeck-it/nextcloud-spreed-signaling
      registry: docker.internal.walbeck.it
      tags:
        - latest
